### ISSUE TITLE
Probably not properly used git resource

### ISSUE THREAD

**Issue by mynkow** [TWChennai/gocd-git-path-material-plugin#11]
Every time a pipeline fails with 17.3 windows 64bit agent we get this error:

```
11:16:28.120 [go] Job Started: 2017-04-17 11:16:28 UTC

11:16:28.120 [go] Start to prepare myPipe/5/Package/1/CreateNuget on MVDC [C:\GA]
11:16:28.214 Clean working directory is set to true. Unable to clean working directory for agent: C:\GA\pipelines\myPipe, with error: Unable to delete file: pipelines\myPipe\local\.git\objects\pack\pack-7424f80058b68300dfd2f2c7e2b67fad474b1e8f.pack
11:16:28.261 [go] Job completed myPipe/5/Package/1/CreateNuget on MVDC [C:\GA]
```

We have to manually restart the GoAgent. This happens only with this plugin.

**Comment by mynkow** [comment]
Do you think that the problem is because of this commit?

https://github.com/TWChennai/gocd-git-path-material-plugin/commit/df9f0d3e7c1fd960e6dc72c0ce9da8c41aca3556

**Comment by mynkow** [comment]
Also this one? => http://stackoverflow.com/questions/19191727/pack-file-from-git-repo-cant-be-deleted-using-file-delete-method

**Comment by jskswamy** [comment]
@mynkow can you try using the [old version 1.2.2](https://github.com/TWChennai/gocd-git-path-material-plugin/releases/tag/1.2.2) and see this error persists?

**Comment by mynkow** [comment]
Yeah, I have tried. It is even worst because the lock happens every time, no matter when the goagent is restarted.

**Comment by mynkow** [comment]
Any updates?

**Comment by SayliS** [comment]
+1

**Comment by mynkow** [comment]
Latest GOCD support this with ignore + revert. This plugin is terrible for windows. Stay away.
