### ISSUE TITLE
Git HTTPS Credentials exposed in error logs when server fails to fetch materials

### ISSUE THREAD

**Issue by adyang-tw** [TWChennai/gocd-git-path-material-plugin#135]
We are using this plugin, in combination with the [gocd-kubernetes-based-secrets-plugin](https://github.com/gocd/gocd-kubernetes-based-secrets-plugin) to specify the username and password to access a Git material over HTTPS with authentication.

When the server fails to clone/ make a git request, the error message exposes the username and password combination, leaking git credentials in the process, e.g.:

> Modification check failed for material: [url=https://gitlab-instance/project.git, username={{SECRET:[deploy-token][username]}}, password={{SECRET:[deploy-token][token]}}, branch=main] Affected pipelines are pipeline-A.
The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '&quot;latest-revision failed due to [RuntimeException: Exception (Process exited with an error: 128 (Exit value: 128)) Occurred: [git, clone, --branch=main, --no-checkout, https://**username**:**exposed-password**@gitlab-instance/project.git, /go/pipelines/mypipeline/my-material] - null], rootCause [ExecuteException: Process exited with an error: 128 (Exit value: 128)]&quot;'

**Comment by chadlwilson** [comment]
Yikes, yeah this isn't good. Probably not noticed it myself before as always used SSH connectivity.

For some historical reason, the `username` isn't classified as a `secure` variable in this plugin, so for consistency for now I'd probably just redact the password field.

Will probably need to take an approach like the GoCD server to redact the error messages. Alternatively, one might argue the GoCD server and/or agent could/should do this (although that wouldn't address issues with plugin-specific logging which the GoCD server doesn't have control over)

**Comment by chadlwilson** [comment]
This should be fixed in https://github.com/TWChennai/gocd-git-path-material-plugin/releases/tag/v2.3.0-356
