### ISSUE TITLE
GOCD Pipeline stuck on past

### ISSUE THREAD

**Issue by ferdinandjmaddela** [TWChennai/gocd-git-path-material-plugin#138]
I have GOCD 19.8.0 with GitPathMaterial Plugin 1.2.3. I cannot upgrade because all the pipeline must run with at MAX java 8.
I have multiple pipeline stuck to an older commit.

Based on log analysis, the flyweight-folder point to the same UUID path and the revision did not change.

There is a way to purge the latest-revision-since or clean up the history to make the pipelines start as a first time poll to git repository?

thanks

**Comment by chadlwilson** [comment]
There are many ways to have the GoCD Agent run with a different Java version to that of the pipelines that are running on it - you can have many JVMs side-by-side on the host (e.g OS packages, or use a Java version manager such as jabba, sdkman, rtx, adsf), or you can dynamically download/install/make available a Java 8 installation when your pipeline starts. I would avoid thinking that the requirements of the builds on your agents to run with Java 8 should not block an upgrade. There are many security vulnerabilities in running a GoCD version that old, and it's unsupported.

Anyway, to your actual question, you can try and remove the flyweight folder and refresh the material to achieve that, but that version of the plugin is so old, and GoCD version so old that I'd be guessing as to what will happen.

**Comment by ferdinandjmaddela** [comment]
Thanks for the reply. Now we are going to plan the upgrade and the impact.

However i already try do remove flyweight but it still knows what's the latest revision of the commit.

**Comment by chadlwilson** [comment]
Are you sure the later commits match the paths in your path expression?

You could try changing the path expression and then changing it back, or something like that. honestly I have little experience with the 1.x plugin version since it uses a very different underlying approach (uses a java git library, rather than the native got executable).

**Comment by ferdinandjmaddela** [comment]
we upgrade to **2.1.1-119**
now pipeline give this problem


Did not find 'scm' plugin with id 'git-path'. Looks like plugin is missing

**Comment by chadlwilson** [comment]
You said you were running java 8 on your server and agents? As explicitly documented, v2.1 won't work with that.

Anyway, look at the logs and do some debugging please. I can't help on such limited information describing a problem.

**Comment by chadlwilson** [comment]
Closing for now, as there's not enough information to help further here.
