### ISSUE TITLE
TFS Git support

### ISSUE THREAD

**Issue by vkosilko** [TWChennai/gocd-git-path-material-plugin#14]
Unable to connect to TFS Git repo:
`Invalid URL format. Should match ^(?:git|ssh|https?|git@[\w-\.]+[\w]+\.[\w]+):(?:\/\/)?[\w\.@:\/~_-]+\.git(?:\/?|\#[\d\w\.\-_]+?)$`
I think it's because URL format doesn't ends with "*.git"
Is it supported with this plugin?
Also need to authenticate with TFS token or domain user. Is it possible?

**Comment by ketan** [comment]
What URL are you using?

**Comment by vkosilko** [comment]
@ketan I use URL, which was copied from TFS:
![image](https://user-images.githubusercontent.com/15325897/33318121-86fcf89e-d44a-11e7-8c32-96d59bf5a075.png)
Unfortunately it's confidential.
