### ISSUE TITLE
Does not support git ssh

### ISSUE THREAD

**Issue by sundbry** [TWChennai/gocd-git-path-material-plugin#15]
This plugin is only working with https:// style git URLs, and fails to connect with git@ style repository URLs.

**Comment by sivaranjanidev** [comment]
I am working on this issue

**Comment by npetzall** [comment]
Made a super simple "fix" https://github.com/npetzall/gocd-git-path-material-plugin/commit/4dfbab4abcde708198d08f4f794e4ec4ae326dad
