### ISSUE TITLE
Update README.md with screenshots of GoCD latest version

### ISSUE THREAD

**Issue by arunvelsriram** [TWChennai/gocd-git-path-material-plugin#18]

**Comment by arunvelsriram** [comment]
Sure. The screenshots in README.md are taken from older version of GoCD. We have to update the [README.md](./README.md) with screenshots from latest version.

You could setup this project locally by following https://github.com/TWChennai/gocd-git-path-material-plugin#docker, take screenshots and update it.

**Comment by GAyan17** [comment]
Thank you :) I will very well work on this issue.

**Comment by arunvelsriram** [comment]
Fixed in #20
